import streamlit as st
import pickle
import os
import numpy as np
import librosa
import urllib.request

# App Layout configuration
st.set_page_config(page_title="Deepfake Voice Detector", page_icon="🎙️", layout="centered")

st.title("🎙️ AI Deepfake Voice Recognition")
st.write("Upload an audio sample below to verify if the speech is authentic or AI-generated synthetic media.")

MODEL_PATH = "voice_deepfake_model.pkl"

# OPTIONAL: Replace this URL with your own direct download link if you host it elsewhere
# (Ensure the URL ends with a direct download action, not a web preview page)
MODEL_URL = "https://github.com/your-username/your-repo-name/releases/download/v1.0/voice_deepfake_model.pkl"

@st.cache_resource
def download_and_load_model():
    """Downloads the model file from a URL if it doesn't exist locally, then loads it."""
    if not os.path.exists(MODEL_PATH):
        with st.spinner("Downloading pre-trained model matrix from cloud storage... Please wait."):
            try:
                urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)
                st.success("Model downloaded successfully!")
            except Exception as e:
                st.error(f"Failed to download model file automatically. Error: {e}")
                st.stop()
                
    with open(MODEL_PATH, 'rb') as file:
        return pickle.load(file)

def extract_features(file_path, max_pad_len=40):
    try:
        audio, sample_rate = librosa.load(file_path, sr=16000, res_type='kaiser_fast')
        mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
        if mfccs.shape[1] < max_pad_len:
            pad_width = max_pad_len - mfccs.shape[1]
            mfccs = np.pad(mfccs, pad_width=((0, 0), (0, pad_width)), mode='constant')
        else:
            mfccs = mfccs[:, :max_pad_len]
        return mfccs.flatten()
    except Exception as e:
        return None

# Load the model via the download wrapper
try:
    model = download_and_load_model()
except Exception as e:
    st.error("Could not load the model file. Ensure it was trained and serialized correctly.")
    st.stop()

# File Uploader
uploaded_file = st.file_uploader("Choose an audio file...", type=["wav", "mp3"])

if uploaded_file is not None:
    st.audio(uploaded_file, format='audio/wav')
    
    temp_filename = "temp_user_input.wav"
    with open(temp_filename, "wb") as f:
        f.write(uploaded_file.getbuffer())
        
    with st.spinner("Analyzing audio frequencies..."):
        features = extract_features(temp_filename)
        
        if features is not None:
            features = features.reshape(1, -1)
            prediction = model.predict(features)[0]
            probabilities = model.predict_proba(features)[0]
            classes = model.classes_
            
            pred_idx = np.where(classes == prediction)[0][0]
            confidence = probabilities[pred_idx] * 100
            
            st.markdown("---")
            st.subheader("Analysis Verdict:")
            
            if prediction == "REAL":
                st.success(f"✅ **REAL**: The audio belongs to an actual human. (Confidence: {confidence:.2f}%)")
            else:
                st.error(f"🚨 **FAKE**: The audio is a synthetic, deepfake voice generated by AI. (Confidence: {confidence:.2f}%)")
        else:
            st.error("Could not process audio format.")
            
    if os.path.exists(temp_filename):
        os.remove(temp_filename)